### ISSUE TITLE
Machine keeps restarting in the loop

### ISSUE THREAD

**Issue by dmiric** [phase2/outrigger-dashboard#6]
I'm trying to setup phase2 outrigger on linux. I made it trough the installation of dnsdock. Compiled rig and I can use it. When I use rig start i get

[INFO] Linux users should use Docker natively for best performance.
[INFO] Please ensure your local Docker setup is compatible with Outrigger.
[INFO] See http://docs.outrigger.sh/getting-started/linux-installation/
[INFO] Launching Dashboard...
b3e88e692bfb5e0bb5c634ecc825b0399a9b4adbc11a333290214783f044141b
[INFO] Outrigger Dashboard is now available at http://dashboard.outrigger.vm
[INFO] Outrigger is ready to use

But I cannot access it on that url

also if i go docker ps in status for dashboard i get Restarting in the loop

CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                                  PORTS                   NAMES
b3e88e692bfb        outrigger/dashboard:latest       "docker-entrypoint..."   6 seconds ago       Restarting (1) Less than a second ago                           outrigger-dashboard

is that a normal behaviour? What am I missing here?

in logs i get

2017-09-24T08:22:05.208401400Z 2017/09/24 08:22:05 Registering Docker Event Listener....
2017-09-24T08:22:05.208454603Z 2017/09/24 08:22:05 Starting HTTP server listening on port :80
2017-09-24T08:22:05.209048144Z 2017/09/24 08:22:05 Error response from daemon: {"message":"page not found"}

➜  rigtest docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

rig version 1.3.1

**Comment by grayside** [comment]
Hi @dmiric 

I'd like to ask a couple clarifying questions to make sure I understand what you are doing.

> I'm trying to setup phase2 outrigger on linux

So you do not currently have Docker installed on Linux and you are now setting up Outrigger?

> I made it trough the installation of dnsdock

Meaning you have seemingly successfully followed the [instructions for DNS support on Linux](http://docs.outrigger.sh/getting-started/linux-installation/)?

Could you provide the output of `rig doctor`?

**Comment by dmiric** [comment]
Thank you for your prompt reply. I figured out some things about the whole outrigger since I posted this. But I still can't exactly grasp the how the whole thing should be working.

1. Yes I have docker installed.
2. Yes I setup dnsdock using your documentation instructions.

**rig doctor output:**
[INFO] Docker is installed.
[INFO] Docker Compose is installed.
[ERROR] No machine named 'dev' exists. Did you run 'rig start --name="dev"'?

I really don't understand what is meant by 'dev' machine?

### Here are some recent discoveries

**If I use:** 
docker run -d --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -l com.dnsdock.name=dashboard \
    -l com.dnsdock.image=outrigger \
    -e DOCKER_API_VERSION=`docker version -f {{.Client.APIVersion}}` \
    --name outrigger-dashboard \
    outrigger/dashboard:latest

Outrigger starts normally and works as intended.

**Here is a gist terminal output I get with all the steps I take to create a new project:**
https://gist.github.com/dmiric/5c437e6935e0173df60a3899b601f0e7

**Comment by febbraro** [comment]
Took a while, but the newest release of `rig` (2.0.0) should be fully Linux compatible. There are release candidates up there now.  RC6 should have this dashboard fix, https://github.com/phase2/rig/pull/117. I plan to publish this later today.

**Comment by febbraro** [comment]
RC6 is released. https://github.com/phase2/rig/releases/tag/2.0.0-rc6
